services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/Api
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - db
    ports:
      - "3030:3030"
    environment:
      - ASPNETCORE_URLS=http://+:3030
      - ASPNETCORE_ENVIRONMENT=Development
      # .NET config keys use double underscores to map nested JSON
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__SecretKey=${JWT_SECRET}
      - CORS__AllowedOrigins=${CORS_ORIGIN}
      - Resend__ApiKey=${RESEND_API_KEY}
      - App__FromEmail=${APP_FROM_EMAIL}
      - Frontend__BaseUrl=${FRONTEND_BASE_URL}
      - Frontend__Domain=${FRONTEND_DOMAIN}

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${API_BASE_URL}
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next

volumes:
  pgdata:
