# fly.toml app configuration file generated for api-billowing-water-633 on 2025-09-04T09:09:30+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-billowing-water-633'
primary_region = 'syd'

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
